export type Status = "Active" | "Notice Period" | "Exited";
export interface Employee { id:string; employeeCode:string; name:string; email:string; phone:string; department:string; designation:string; manager:string; joiningDate:string; employmentType:"Full-time"|"Intern"|"Consultant"|"Mentor"; salary:number; workLocation:string; status:Status; avatar:string; skills:string[]; documents:string[] }
export interface Department { id:string; name:string; head:string; employeeCount:number; budget:number; status:string }
export interface Attendance { id:string; employeeId:string; date:string; checkIn:string; checkOut:string; workMode:"Office"|"Remote"|"Hybrid"|"Leave"; status:"Not Checked In"|"Present"|"Absent"|"Half Day"|"Leave"|"Late"; workingHours:number; regularizationStatus:"None"|"Pending"|"Approved"|"Rejected"; regularizationReason?:string; correctedCheckIn?:string; correctedCheckOut?:string; leaveRequestId?:string; approvedBy?:string; remarks?:string }
export interface Leave { id:string; employeeId:string; leaveType:"Casual"|"Sick"|"Earned"|"Unpaid"; fromDate:string; toDate:string; days:number; reason:string; status:"Pending"|"Approved"|"Rejected"; managerRemarks:string; createdAt?:string; approvedBy?:string; approvedAt?:string; rejectedBy?:string; rejectedAt?:string }
export interface Payroll { id:string; employeeId:string; month:string; basicSalary:number; allowances:number; deductions:number; lop:number; lopDays?:number; netSalary:number; status:"Draft"|"Processed"|"Paid"; paymentDate:string; generatedAt?:string; processedAt?:string; processedBy?:string; paidBy?:string }
export interface Project { id:string; projectCode:string; name:string; client:string; manager:string; startDate:string; deadline:string; assignedMembers:string[]; budget:number; revenue:number; progress:number; status:"Not Started"|"In Progress"|"Review"|"Completed"; health:"Green"|"Yellow"|"Red"; priority:"Low"|"Medium"|"High"|"Critical" }
export interface Task { id:string; projectId:string; title:string; description:string; assignedTo:string; priority:"Low"|"Medium"|"High"|"Critical"; dueDate:string; estimatedHours:number; actualHours:number; status:"Backlog"|"To Do"|"In Progress"|"Review"|"Done" }
export interface Timesheet { id:string; employeeId:string; projectId:string; taskId:string; date:string; hoursWorked:number; type:"Billable"|"Non-billable"; description:string; approvalStatus:"Pending"|"Approved"|"Rejected"; submittedAt?:string; approvedBy?:string; approvedAt?:string; rejectedBy?:string; rejectedAt?:string; managerRemarks?:string }
export interface Student { id:string; studentCode:string; name:string; email:string; phone:string; college:string; degree:string; graduationYear:number; skills:string[]; careerInterest:string; sprintHistory:string[]; readinessScore:number; portfolioLink:string; mentorFeedback:string; ppoStatus:"Not Eligible"|"Eligible"|"Recommended"|"Offered"|"Hired"; status:"Registered"|"Sprint Applied"|"Selected"|"In Training"|"Internship Deployed"|"PPO Recommended"|"Hired" }
export interface CareerSprint { id:string; sprintCode:string; name:string; domain:string; corporatePartner:string; mentor:string; startDate:string; endDate:string; studentsEnrolled:number; completionRate:number; averageReadinessScore:number; pposIssued:number; status:"Upcoming"|"Live"|"Completed"; description:string }
export interface CorporatePartner { id:string; companyName:string; contactPerson:string; email:string; phone:string; industry:string; hiringNeed:string; activeSprints:number; internsDeployed:number; pposIssued:number; revenueGenerated:number; accountOwner:string; status:"Lead"|"Active Partner"|"Dormant"|"Closed" }
export interface InternDeployment { id:string; studentId:string; internName:string; corporateClient:string; projectAssigned:string; mentor:string; startDate:string; endDate:string; attendancePercentage:number; timesheetCompliance:number; taskCompletion:number; clientFeedback:number; performanceScore:number; ppoProbability:number; status:"Shortlisted"|"Deployed"|"Active"|"Completed"|"PPO Offered"|"Not Offered" }
export interface ReadinessScore { id:string; studentId:string; taskCompletion:number; mentorFeedback:number; clientFeedback:number; attendance:number; communication:number; timesheetDiscipline:number; finalScore:number; recommendation:"Needs Training"|"Internship Ready"|"PPO Ready"|"High Potential"; strengths:string[]; improvementAreas:string[] }
export interface Invoice { id:string; invoiceNumber:string; client:string; projectOrSprint:string; amount:number; dueDate:string; paymentStatus:"Draft"|"Sent"|"Paid"|"Overdue"; revenueCategory:string; createdAt:string }
export interface Expense { id:string; category:string; description:string; amount:number; date:string; status:"Pending"|"Approved"|"Rejected"|"Paid" }
export interface Asset { id:string; assetCode:string; assetType:string; assignedTo:string; issueDate:string; condition:string; returnStatus:string; status:string }
export interface Document { id:string; title:string; documentType:string; owner:string; uploadedDate:string; status:"Uploaded"|"Verified"|"Rejected"|"Expired" }
export interface Ticket { id:string; ticketNumber:string; title:string; category:"HR Issue"|"IT Access"|"Payroll Issue"|"Attendance Correction"|"Asset Issue"|"Project Blocker"; raisedBy:string; assignedTo:string; priority:string; status:"Open"|"Assigned"|"In Progress"|"Resolved"|"Closed"; createdAt:string }
export interface Role { id:string; name:string; permissions:string[] }
export interface Notification { id:string; userId?:string; roleTarget?:string; title:string; message:string; type:"Info"|"Success"|"Warning"|"Danger"; relatedModule:string; isRead:boolean; createdAt:string }
