import { Navigate, type RouteObject } from "react-router-dom";
import type { ReactNode } from "react";
import { AppLayout } from "../components/layout/AppLayout";
import { AuthorizedRoute } from "../auth/AuthorizedRoute";
import { ProtectedRoute } from "../auth/ProtectedRoute";
import { PageShell } from "../components/layout/PageShell";
import { AttendancePage } from "../features/attendance/AttendancePage";
import { DashboardPage } from "../features/dashboard/DashboardPage";
import { LeavePage } from "../features/leave/LeavePage";
import { LoginPage } from "../features/auth/LoginPage";
import { PayrollPage } from "../features/payroll/PayrollPage";
import { TimesheetsPage } from "../features/timesheets/TimesheetsPage";
import { ModulePage } from "../features/shared/ModulePage";
import { useAppStore } from "../store/useAppStore";
import { inr } from "../lib/utils";

const employeeFields = ["employeeCode","name","email","phone","department","designation","manager","employmentType","salary","workLocation","status"];
const studentFields = ["studentCode","name","email","phone","college","degree","graduationYear","careerInterest","readinessScore","ppoStatus","status"];
const projectFields = ["projectCode","name","client","manager","deadline","budget","revenue","progress","priority","status","health"];
const taskFields = ["title","description","assignedTo","priority","dueDate","estimatedHours","actualHours","status"];
const moneyStats = () => {
  const s = useAppStore.getState();
  return [
    { label:"Revenue", value:inr(s.invoices.reduce((a,b)=>a+b.amount,0)) },
    { label:"Expenses", value:inr(s.expenses.reduce((a,b)=>a+b.amount,0)) },
    { label:"Payroll Cost", value:inr(s.payroll.reduce((a,b)=>a+b.netSalary,0)) },
    { label:"Pending Payments", value:s.invoices.filter(i=>i.paymentStatus!=="Paid").length }
  ];
};

function Shell({ title, description, children }: { title:string; description?:string; children:ReactNode }) { return <PageShell title={title} description={description}>{children}</PageShell>; }
function Placeholder({ title, collection, description }: { title:string; collection:any; description:string }) {
  const s:any = useAppStore.getState(); const rows = s[collection] || s.employees;
  return <Shell title={title} description={description}><ModulePage title={title} description={description} collection={collection} fields={Object.keys(rows[0] || {}).filter(k=>k!=="id").slice(0,8)} stats={[{label:"Total Records",value:rows.length},{label:"Active Items",value:rows.filter((r:any)=>String(r.status).includes("Active")).length || rows.length},{label:"Pending",value:rows.filter((r:any)=>String(r.status).includes("Pending")).length},{label:"Operational Health",value:"92%"}]} progressKey={rows[0]?.progress!==undefined?"progress":undefined}/></Shell>;
}

export const routes: RouteObject[] = [
{ path:"/login", element:<LoginPage/> },
{ element:<ProtectedRoute/>, children:[{ path:"/", element:<AppLayout/>, children:[{ element:<AuthorizedRoute/>, children:[
  { index:true, element:<Navigate to="/dashboard" replace/> },
  { path:"dashboard", element:<Shell title="Executive Dashboard" description="Live command center for AntBox people, projects, sprints, readiness, deployment, and finance."><DashboardPage/></Shell> },
  { path:"employees", element:<Shell title="Employees" description="HRMS employee master with department, role, salary, documents, and employment status."><ModulePage title="Employees" description="" collection="employees" fields={employeeFields} editable stats={[{label:"Total Employees",value:useAppStore.getState().employees.length},{label:"Active Employees",value:useAppStore.getState().employees.filter(e=>e.status==="Active").length},{label:"Interns",value:useAppStore.getState().employees.filter(e=>e.employmentType==="Intern").length},{label:"Payroll Cost",value:inr(useAppStore.getState().payroll.reduce((a,b)=>a+b.netSalary,0))}]}/></Shell> },
  { path:"interns", element:<Shell title="Interns" description="Intern employees and deployed talent tracked across attendance, projects, and PPO outcomes."><ModulePage title="Interns" description="" collection="deployments" fields={["internName","corporateClient","projectAssigned","mentor","performanceScore","ppoProbability","status"]} stats={[{label:"Active Interns",value:useAppStore.getState().deployments.length},{label:"Avg Performance",value:"85%"},{label:"PPO Pipeline",value:useAppStore.getState().deployments.filter(d=>d.ppoProbability>80).length},{label:"Clients",value:new Set(useAppStore.getState().deployments.map(d=>d.corporateClient)).size}]} progressKey="ppoProbability"/></Shell> },
  { path:"students", element:<Shell title="Students" description="Student CRM for career sprint enrollment, readiness, portfolios, and PPO stage tracking."><ModulePage title="Students" description="" collection="students" fields={studentFields} editable stats={[{label:"Active Students",value:useAppStore.getState().students.length},{label:"Avg Readiness",value:"85%"},{label:"PPO Recommended",value:useAppStore.getState().students.filter(s=>s.ppoStatus==="Recommended").length},{label:"Colleges",value:new Set(useAppStore.getState().students.map(s=>s.college)).size}]} progressKey="readinessScore"/></Shell> },
  { path:"departments", element:<Placeholder title="Departments" collection="departments" description="Department budgets, heads, headcount, and operating ownership."/> },
  { path:"attendance", element:<Shell title="Attendance" description="Check in, check out, track today status, and review your monthly attendance."><AttendancePage/></Shell> },
  { path:"leave", element:<Shell title="Leave" description="Apply leave, track balances, and manage HR approvals."><LeavePage/></Shell> },
  { path:"payroll", element:<Shell title="Payroll" description="Generate monthly payroll using salary, attendance, leave, and LOP."><PayrollPage/></Shell> },
  { path:"projects", element:<Shell title="Projects" description="Client projects, sprint delivery, budgets, revenue, progress, and project health."><ModulePage title="Projects" description="" collection="projects" fields={projectFields} editable stats={[{label:"Active Projects",value:useAppStore.getState().projects.filter(p=>p.status!=="Completed").length},{label:"Revenue",value:inr(useAppStore.getState().projects.reduce((a,b)=>a+b.revenue,0))},{label:"At Risk",value:useAppStore.getState().projects.filter(p=>p.health==="Red").length},{label:"Avg Progress",value:"53%"}]} progressKey="progress"/></Shell> },
  { path:"tasks", element:<Shell title="Tasks" description="Kanban workflow for sprint/project assignments, delivery tasks, and review status."><ModulePage title="Tasks" description="Mentors and project managers move work from backlog to done." collection="tasks" fields={taskFields} editable kanban stats={[{label:"Total Tasks",value:useAppStore.getState().tasks.length},{label:"In Progress",value:useAppStore.getState().tasks.filter(t=>t.status==="In Progress").length},{label:"Review",value:useAppStore.getState().tasks.filter(t=>t.status==="Review").length},{label:"Done",value:useAppStore.getState().tasks.filter(t=>t.status==="Done").length}]}/></Shell> },
  { path:"timesheets", element:<Shell title="Timesheets" description="Submit work logs, review approvals, and track billable utilization."><TimesheetsPage/></Shell> },
  { path:"career-sprints", element:<Shell title="Career Sprints" description="Corporate hosted readiness sprints with mentors, enrollment, completion, and PPO output."><ModulePage title="Career Sprints" description="" collection="sprints" fields={["sprintCode","name","domain","corporatePartner","mentor","studentsEnrolled","completionRate","averageReadinessScore","pposIssued","status"]} stats={[{label:"Live Sprints",value:useAppStore.getState().sprints.filter(s=>s.status==="Live").length},{label:"Students Enrolled",value:useAppStore.getState().sprints.reduce((a,b)=>a+b.studentsEnrolled,0)},{label:"Completion",value:"65%"},{label:"PPOs Issued",value:useAppStore.getState().sprints.reduce((a,b)=>a+b.pposIssued,0)}]} progressKey="completionRate"/></Shell> },
  { path:"corporate-partners", element:<Shell title="Corporate Partners" description="Partner CRM for hiring needs, sprints, deployments, revenue, and PPO outcomes."><ModulePage title="Corporate Partners" description="" collection="partners" fields={["companyName","contactPerson","industry","hiringNeed","activeSprints","internsDeployed","pposIssued","revenueGenerated","accountOwner","status"]} stats={[{label:"Partners",value:useAppStore.getState().partners.length},{label:"Revenue",value:inr(useAppStore.getState().partners.reduce((a,b)=>a+b.revenueGenerated,0))},{label:"Interns Deployed",value:useAppStore.getState().partners.reduce((a,b)=>a+b.internsDeployed,0)},{label:"PPOs",value:useAppStore.getState().partners.reduce((a,b)=>a+b.pposIssued,0)}]}/></Shell> },
  { path:"intern-deployment", element:<Shell title="Intern Deployment" description="Deployment pipeline with performance, attendance, timesheet compliance, client feedback, and PPO probability."><ModulePage title="Intern Deployment" description="" collection="deployments" fields={["internName","corporateClient","projectAssigned","mentor","attendancePercentage","timesheetCompliance","taskCompletion","clientFeedback","performanceScore","ppoProbability","status"]} stats={[{label:"Deployed",value:useAppStore.getState().deployments.length},{label:"Avg Performance",value:"85%"},{label:"High PPO Probability",value:useAppStore.getState().deployments.filter(d=>d.ppoProbability>80).length},{label:"Client Feedback",value:"84%"}]} progressKey="ppoProbability"/></Shell> },
  { path:"readiness-scores", element:<Shell title="Readiness Scores" description="AI-simulated readiness scoring across task completion, mentor feedback, client feedback, attendance, communication, and timesheet discipline."><ModulePage title="Readiness Scores" description="" collection="readinessScores" fields={["studentId","taskCompletion","mentorFeedback","clientFeedback","attendance","communication","timesheetDiscipline","finalScore","recommendation"]} stats={[{label:"Average Score",value:"85%"},{label:"PPO Ready",value:useAppStore.getState().readinessScores.filter(r=>r.recommendation==="PPO Ready" || r.recommendation==="High Potential").length},{label:"Needs Training",value:useAppStore.getState().readinessScores.filter(r=>r.recommendation==="Needs Training").length},{label:"Measured Factors",value:6}]} progressKey="finalScore"/></Shell> },
  { path:"ppo-tracker", element:<Shell title="PPO Tracker" description="Candidate pipeline across recommended, offered, hired, and not offered outcomes."><ModulePage title="PPO Tracker" description="" collection="students" fields={["studentCode","name","college","careerInterest","readinessScore","ppoStatus","status"]} stats={[{label:"Recommended",value:useAppStore.getState().students.filter(s=>s.ppoStatus==="Recommended").length},{label:"Offered",value:useAppStore.getState().students.filter(s=>s.ppoStatus==="Offered").length},{label:"Hired",value:useAppStore.getState().students.filter(s=>s.ppoStatus==="Hired").length},{label:"Conversion",value:"70%"}]} progressKey="readinessScore"/></Shell> },
  { path:"finance", element:<Navigate to="/finance/invoices" replace/> },
  { path:"finance/invoices", element:<Shell title="Finance" description="Revenue dashboard, invoices, expenses, payroll cost, profitability, and pending payments."><ModulePage title="Invoices" description="" collection="invoices" fields={["invoiceNumber","client","projectOrSprint","amount","dueDate","revenueCategory","createdAt","paymentStatus"]} editable stats={moneyStats()}/></Shell> },
  { path:"finance/expenses", element:<Shell title="Expenses" description="Operational, mentor, software, and project expenses."><ModulePage title="Expenses" description="" collection="expenses" fields={["category","description","amount","date","status"]} editable stats={moneyStats()}/></Shell> },
  { path:"finance/payroll-cost", element:<Shell title="Payroll Cost" description="Payroll cost view connected to monthly salary processing."><ModulePage title="Payroll Cost" description="" collection="payroll" fields={["employeeId","month","basicSalary","allowances","deductions","lop","netSalary","status"]} stats={moneyStats()}/></Shell> },
  { path:"finance/profitability", element:<Shell title="Profitability" description="Project and sprint profitability snapshot."><ModulePage title="Profitability" description="" collection="projects" fields={["projectCode","name","client","budget","revenue","progress","health","status"]} stats={moneyStats()} progressKey="progress"/></Shell> },
  { path:"assets", element:<Shell title="Assets" description="Laptop, ID card, email, software access, monitor, and device allocations."><ModulePage title="Assets" description="" collection="assets" fields={["assetCode","assetType","assignedTo","issueDate","condition","returnStatus","status"]} stats={[{label:"Assets",value:useAppStore.getState().assets.length},{label:"Assigned",value:useAppStore.getState().assets.filter(a=>a.status==="Assigned").length},{label:"Returns Due",value:1},{label:"Good Condition",value:2}]}/></Shell> },
  { path:"documents", element:<Shell title="Documents" description="Offer letters, internship letters, NDAs, certificates, payslips, contracts, invoices, and portfolios."><ModulePage title="Documents" description="" collection="documents" fields={["title","documentType","owner","uploadedDate","status"]} stats={[{label:"Documents",value:useAppStore.getState().documents.length},{label:"Verified",value:useAppStore.getState().documents.filter(d=>d.status==="Verified").length},{label:"Uploaded",value:useAppStore.getState().documents.filter(d=>d.status==="Uploaded").length},{label:"Expired",value:0}]}/></Shell> },
  { path:"helpdesk", element:<Shell title="Helpdesk Tickets" description="HR, IT access, payroll, attendance correction, asset, and project blocker support queue."><ModulePage title="Helpdesk Tickets" description="" collection="tickets" fields={["ticketNumber","title","category","raisedBy","assignedTo","priority","createdAt","status"]} editable stats={[{label:"Open Tickets",value:useAppStore.getState().tickets.filter(t=>t.status!=="Closed" && t.status!=="Resolved").length},{label:"Resolved",value:useAppStore.getState().tickets.filter(t=>t.status==="Resolved").length},{label:"High Priority",value:useAppStore.getState().tickets.filter(t=>t.priority==="High").length},{label:"Avg SLA",value:"18h"}]}/></Shell> },
  { path:"roles-permissions", element:<Shell title="Roles & Permissions" description="Permission matrix for AntBox operating roles."><ModulePage title="Roles & Permissions" description="" collection="roles" fields={["name","permissions"]} stats={[{label:"Roles",value:useAppStore.getState().roles.length},{label:"Admin Roles",value:5},{label:"Portal Roles",value:4},{label:"Permission Areas",value:24}]}/></Shell> },
  { path:"onboarding", element:<Placeholder title="Onboarding" collection="employees" description="Offer, joining, document verification, account setup, and induction workflow."/> },
  { path:"exit-management", element:<Placeholder title="Exit Management" collection="employees" description="Notice period, asset returns, access revocation, and final settlement tracking."/> },
  { path:"deliverables", element:<Placeholder title="Deliverables" collection="tasks" description="Client deliverables mapped to project tasks, owners, review status, and due dates."/> },
  { path:"mentors", element:<Placeholder title="Mentors" collection="employees" description="Mentor availability, sprint ownership, student feedback, and review load."/> },
  { path:"certificates", element:<Placeholder title="Certificates" collection="documents" description="Career sprint certificates and verified student credentials."/> },
  { path:"client-feedback", element:<Placeholder title="Client Feedback" collection="deployments" description="Client feedback scores by intern, project, sprint, and PPO opportunity."/> },
  { path:"settings", element:<Placeholder title="Settings" collection="roles" description="Workspace configuration, operating preferences, integrations, and data controls."/> },
  { path:"*", element:<Navigate to="/dashboard" replace/> }
] }] }] }
];
